trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToAzureVM
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y apache2
    displayName: 'Install Apache'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
    displayName: 'Copy HTML files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
      artifactName: 'publishedWebsite'
      publishLocation: 'Container'

  - task: SSH@0
    inputs:
      sshEndpoint: 'azurevm'  # Replace with the name of your SSH service connection
      runOptions: 'inline'
      scriptInline: |
        sudo rm -rf /var/www/html/*
        sudo cp -r $(System.DefaultWorkingDirectory)/publishedWebsite/* /var/www/html/
        sudo systemctl restart apache2
    displayName: 'Deploy to Azure VM'